[profile.default]
solc = "0.8.33"
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
